/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package activity;

import javax.persistence.EntityManager;

public class App {

    public static void main(String[] args) {
        ConexionOBD conexionOBD = new ConexionOBD("miUnidadPersistencia");
        
        try {
            EntityManager entityManager = conexionOBD.getEM();
        }catch(Exception e){
            System.out.println(e);
        }
    }
}
